"use client";

import { motion } from "framer-motion";
import { staggerContainer, staggerItem } from "@/lib/animations";
import GlassCard from "@/components/ui/GlassCard";
import PulseIndicator from "@/components/ui/PulseIndicator";
import { insights } from "@/lib/mock-data";
import { Sparkles, TrendingUp, Gavel, AlertTriangle, LineChart } from "lucide-react";

const iconMap: Record<string, typeof Sparkles> = {
  auto_awesome: Sparkles,
  trending_up: TrendingUp,
  gavel: Gavel,
  warning: AlertTriangle,
  show_chart: LineChart,
};

export default function FeedPage() {
  return (
    <div className="p-4 md:p-6 max-w-[900px] mx-auto">
      <motion.div variants={staggerContainer} initial="initial" animate="animate">
        {/* Header */}
        <motion.div variants={staggerItem} className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <PulseIndicator color="cyan" label="LIVE FEED" />
          </div>
          <h1 className="font-geist text-4xl md:text-5xl font-extrabold text-on-surface mb-2">
            AI Insight Feed
          </h1>
          <p className="text-on-surface-variant text-lg">
            Real-time intelligence updates, auto-generated by AI core.
          </p>
        </motion.div>

        {/* Filters */}
        <motion.div variants={staggerItem} className="flex gap-2 mb-6 overflow-x-auto pb-2">
          {["All", "AI Synthesis", "Volume Spikes", "Policy", "Alerts"].map(
            (filter, i) => (
              <button
                key={filter}
                className={`px-4 py-2 rounded-lg font-mono text-label-caps tracking-wider whitespace-nowrap transition-all ${
                  i === 0
                    ? "bg-primary-container text-on-primary-container"
                    : "bg-surface-container border border-white/10 text-on-surface-variant hover:border-primary-fixed/30"
                }`}
              >
                {filter}
              </button>
            )
          )}
        </motion.div>

        {/* Feed */}
        <div className="space-y-4">
          {insights.map((insight, i) => {
            const Icon = iconMap[insight.icon] || Sparkles;

            return (
              <motion.div key={insight.id} variants={staggerItem}>
                <GlassCard
                  variant={insight.type === "ai_synthesis" ? "ai" : insight.urgency === "high" ? "active" : "default"}
                  delay={i * 0.08}
                  className="relative"
                >
                  {/* Urgency Indicator */}
                  {insight.urgency === "high" && (
                    <div className="absolute top-0 right-0 w-24 h-24 bg-error/10 blur-3xl rounded-full" />
                  )}

                  <div className="flex gap-4">
                    {/* Icon */}
                    <div
                      className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 ${
                        insight.type === "ai_synthesis"
                          ? "bg-ai-purple/20 border border-ai-purple/30"
                          : insight.type === "alert"
                          ? "bg-error/20 border border-error/30"
                          : "bg-surface-container border border-white/10"
                      }`}
                    >
                      <Icon
                        size={18}
                        className={
                          insight.type === "ai_synthesis"
                            ? "text-ai-purple"
                            : insight.type === "alert"
                            ? "text-error"
                            : "text-primary-fixed"
                        }
                      />
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2">
                        <span
                          className={`font-mono text-label-caps tracking-wider uppercase ${
                            insight.type === "ai_synthesis"
                              ? "text-ai-purple"
                              : insight.type === "alert"
                              ? "text-error"
                              : "text-on-surface-variant"
                          }`}
                        >
                          {insight.label}
                        </span>
                        <span className="font-mono text-[10px] text-on-surface-variant/40">
                          {insight.timestamp}
                        </span>
                        {insight.confidence && (
                          <span className="ml-auto px-2 py-0.5 bg-surface-container border border-white/10 rounded font-mono text-[10px] text-on-surface-variant">
                            {insight.confidence}% conf
                          </span>
                        )}
                      </div>

                      <h3 className="font-geist text-lg font-bold text-on-surface mb-2">
                        {insight.title}
                      </h3>

                      <p className="text-on-surface-variant text-sm leading-relaxed mb-3">
                        {insight.description}
                      </p>

                      {insight.metric && (
                        <div className="mb-3">
                          <div className="h-1.5 bg-surface-container-highest rounded-full overflow-hidden mb-1">
                            <motion.div
                              className="h-full bg-primary-fixed rounded-full"
                              initial={{ width: 0 }}
                              animate={{ width: `${insight.metric.percentage}%` }}
                              transition={{ duration: 1, delay: 0.5 + i * 0.1 }}
                            />
                          </div>
                          <div className="flex justify-between font-mono text-[10px] text-on-surface-variant/50">
                            <span>{insight.metric.baseline}</span>
                            <span className="text-primary-fixed">
                              {insight.metric.current}
                            </span>
                          </div>
                        </div>
                      )}

                      {insight.tags.length > 0 && (
                        <div className="flex flex-wrap gap-2">
                          {insight.tags.map((tag) => (
                            <span
                              key={tag}
                              className="px-2 py-0.5 bg-surface-container border border-white/5 rounded font-mono text-[10px] text-on-surface-variant"
                            >
                              {tag}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </GlassCard>
              </motion.div>
            );
          })}
        </div>
      </motion.div>
    </div>
  );
}
